M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Fri 26 Jan 2024 16:09:17 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-26T16:09:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X45.5Y-28.5
X97.5Y-42.43
X114.0Y-28.5
X124.5Y-42.43
T2
X48.5Y-90.5
X151.5Y-31.5
X151.5Y-90.5
T0
M30
