# Default initial positions for ttk4900_orca's ros2_control fake system

initial_positions:
  joint_base_torso: 0
  joint_hand_twist: 0
  joint_lower_arm_hand: 0
  joint_torso_upper_arm: 0
  joint_twist_gripper0: 0
  joint_twist_gripper1: 0
  joint_upper_lower_arm: 0