# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_base_torso:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: true
    max_acceleration: 2.0
  joint_hand_twist:
    has_velocity_limits: true
    max_velocity: 3.00000000000000000
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint_lower_arm_hand:
    has_velocity_limits: true
    max_velocity: 0.4000000000000001
    has_acceleration_limits: true
    max_acceleration: 4.0
  joint_torso_upper_arm:
    has_velocity_limits: true
    max_velocity: 0.4000000000000001
    has_acceleration_limits: true
    max_acceleration: 4.0
  joint_twist_gripper0:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: true
    max_acceleration: 2.0
  joint_twist_gripper1:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: true
    max_acceleration: 2.0
  joint_upper_lower_arm:
    has_velocity_limits: true
    max_velocity: 0.4000000000000001
    has_acceleration_limits: true
    max_acceleration: 4.0