# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - orca_arm_controller
    - orca_hand_controller

  orca_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_base_torso
      - joint_torso_upper_arm
      - joint_upper_lower_arm
      - joint_lower_arm_hand
      - joint_hand_twist
    action_ns: follow_joint_trajectory
    default: true
  orca_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_twist_gripper0
      - joint_twist_gripper1
    action_ns: follow_joint_trajectory
    default: true