# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    orca_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    orca_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

orca_arm_controller:
  ros__parameters:
    joints:
      - joint_base_torso
      - joint_torso_upper_arm
      - joint_upper_lower_arm
      - joint_lower_arm_hand
      - joint_hand_twist
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true

orca_hand_controller:
  ros__parameters:
    joints: 
      - joint_twist_gripper0
      - joint_twist_gripper1
    command_interfaces:
      - position
    state_interfaces:
      - position      