M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Fri 26 Jan 2024 15:24:35 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-26T15:24:35+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X79.85Y-59.55
X124.5Y-59.55
T0
M30
