M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Fri 26 Jan 2024 15:42:48 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-26T15:42:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X88.5Y-65.982
X116.0Y-65.982
T0
M30
